### PR TITLE
Add validation for organization numbers in the exhibitor registration form

### PR DESCRIPTION
**Pull request by mathiasmagnusson**
Depends on #10. Don't merge this before that one.

### CODE REVIEW

**Comment by mathiasmagnusson** [comment]
If we go through with Bolagverket's API, then perhaps we don't want to use this validation.

**Comment by ernum** [comment]
> If we go through with Bolagverket's API, then perhaps we don't want to use this validation.

Yes, maybe we should wait with this PR until we hear back regarding the API. On the other hand, if we create a python script with the API this validation might still be useful.

**Comment by mathiasmagnusson** [comment]
Yes, it's still nice to validate what we can on the client.

I've now merged stuff

**Review by ernum — APPROVED** [review]
LGTM

**Pull request merged**
