### PR TITLE
För företag sida

### PR DESCRIPTION
**Pull request by Eggetxd**

### CODE REVIEW

**Comment by mathiasmagnusson** [comment]
On medium-sized screens, some things collide a bit:
image

**Comment by Eggetxd** [comment]
> On medium-sized screens, some things collide a bit: image

fixade det

**Comment by Eggetxd** [comment]
> The mobile version looks identical to its design on figma. However, the desktop version differs in the layout. bild
> 
> Is this intentional? @mathiasmagnusson

There is 2 different designs on figma so I just picked one, might have been the earlier design, im not sure

**Comment by mathiasmagnusson** [comment]
> The mobile version looks identical to its design on figma. However, the desktop version differs in the layout.
> 
> Is this intentional? @mathiasmagnusson

Nope - it was just firefox and chrome not agreeing upon what a *baseline* is. Fixed now!

**Review by rikaznismi — CHANGES_REQUESTED** [review]
Spelling error: "Intrested" -> "Interested"

**Review by rikaznismi — APPROVED** [review]

**Pull request merged**
